# This is a basic workflow to help you get started with Actions

name: cd

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cd:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: build image
        run: docker build -t peterstormio/wedding .
      - name: tag image
        run: |
          docker tag peterstormio/wedding ${{ secrets.DOCKER_USERNAME }}/wedding:${{ github.sha }}
          docker tag peterstormio/wedding ${{ secrets.DOCKER_USERNAME }}/wedding:latest
      - name: push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/wedding:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/wedding:latest
      - name: checkout helm repo and update image tag
        uses: actions/checkout@v2
        with:
          repository: peterstorm/wedding-static-argo
          token: ${{ secrets.ACCESS_TOKEN }}
          path: './wedding-static-argo'
      - name: change image tag in helm repo
        uses: mikefarah/yq@master
        with:
          cmd: yq eval -i '.image.tag = ${{ github.sha}}' './wedding-static-argo/wedding/values.yaml'
      - name: push helm repo changes
        run: |
          cd wedding-static-argo &&
          git add . &&
          git commit -m "commit from github actions" &&
          git push origin main
      
