# This is a basic workflow to help you get started with Actions

name: cd

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: build image
        run: docker build -t peterstormio/wedding .
      - name: tag image
        run: |
          docker tag peterstormio/wedding ${{ secrets.DOCKER_USERNAME }}/wedding:${{ github.sha }}
          docker tag peterstormio/wedding ${{ secrets.DOCKER_USERNAME }}/wedding:latest
      - name: push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/wedding:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/wedding:latest
      - name: checkout helm repo
        uses: actions/checkout@v2
        with:
          repository: peterstorm/wedding-static-argo
          token: ${{ secrets.ACCESS_TOKEN }}
          path: './wedding-static-argo'
      - name: change image tag in helm repo
        uses: mikefarah/yq@master
        with:
          cmd: yq eval -i '.image.tag = "${{ github.sha}}"' './wedding-static-argo/wedding/values.yaml'
      - name: push helm repo changes
        run: |
          cd wedding-static-argo &&
          git config --global user.name 'Peter Storm' &&
          git config --global user.email 'peter.storm@peterstorm.io' &&
          git add . &&
          git commit -m "commit from github actions" &&
          git push origin main
      
